language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t esinghal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true esinghal/docker-react npm run test -- --coverage 
